---
# tasks file for undercloud-install

- name: Install Undercloud Block
  block:
    - name: Install undercloud
      shell: |
        set -o pipefail
        { time openstack undercloud install 2>&1 | tee -a {{log_dir}}/install-undercloud.log ; } 2>> {{log_dir}}/install-undercloud.log

    # (akrzos) Workaround for OSP11 Ocata where Keystone is deployed as a
    # singular process hosted in httpd.
    - name: OSP11/Ocata - Tune Keystone processes to 24
      become: true
      lineinfile:
        dest: "{{item}}"
        state: present
        regexp: '^([\t\s]*WSGIDaemonProcess.*)processes=[0-9]+ threads=[0-9]+(.*)$'
        line: '\1processes=24 threads=6\2'
        backup: true
        backrefs: true
      with_items:
        - /etc/httpd/conf.d/10-keystone_wsgi_admin.conf
        - /etc/httpd/conf.d/10-keystone_wsgi_main.conf
      when: version == '11'

    - name: OSP11/Ocata - Restart httpd hosting Keystone
      become: true
      service:
        name: httpd
        state: restarted
      when: version == '11'

    - name: Install ipa and overcloud images
      become: true
      yum: name={{item}}
      with_items:
        - rhosp-director-images
        - rhosp-director-images-ipa

    - name: Untar ipa and overcloud images
      command: "tar -xvf {{item}} -C /home/stack/images"
      with_items:
        - "/usr/share/rhosp-director-images/overcloud-full-latest-{{version}}.0.tar"
        - "/usr/share/rhosp-director-images/ironic-python-agent-latest-{{version}}.0.tar"

    - name: Add debugging root password to images
      shell: "cd /home/stack/images; virt-customize -a overcloud-full.qcow2 --root-password password:{{overcloud_image_password}}"
      environment:
        LIBGUESTFS_BACKEND: direct

    - name: Upload images
      shell: . /home/stack/stackrc; openstack overcloud image upload --image-path /home/stack/images/
  rescue:
    - name: Update motd on failure
      include_role:
        name: update-motd
      vars:
        update_motd: Undercloud install failed

    - name: Ensure playbook stops under this condition
      fail:
        msg: Undercloud install failures
  always:
    - name: Collect undercloud.conf
      become: true
      shell: |
        cp /home/stack/undercloud.conf {{log_dir}}/undercloud.conf

    - name: Collect Install Undercloud Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/alderaan-deploy_log"
        mode: pull

- name: Get neutron subnet uuid
  shell: |
    . /home/stack/stackrc
    neutron subnet-list | grep start | awk '{print $2}'
  register: neutron_subnet_uuid

- name: Setup DNS on Undercloud Neutron subnet
  shell: |
    . /home/stack/stackrc
    neutron subnet-update {{neutron_subnet_uuid.stdout}} --dns-nameserver {{dns_server}}

- name: Setup Container Registry Block
  when: version == '13'
  block:
    - name: Append additional insecure registry to /etc/sysconfig/docker
      become: true
      lineinfile:
        path: /etc/sysconfig/docker
        state: present
        regexp: '^INSECURE_REGISTRY='
        line: 'INSECURE_REGISTRY="--insecure-registry 192.168.0.1:8787 --insecure-registry 192.168.0.3:8787 --insecure-registry {{additional_insecure_registry}} --insecure-registry {{additional_ceph_insecure_registry}} "'

    - name: Restart Docker registry
      become: true
      service:
        name: docker
        state: restarted

    - name: Create template to pull images to local registry
      shell: |
        . /home/stack/stackrc
        openstack overcloud container image prepare \
          --namespace {{additional_insecure_registry}}{{container_namespace}} \
          --prefix openstack --tag {{container_tag}} --push-destination 192.168.0.1:8787 \
          -e /usr/share/openstack-tripleo-heat-templates/environments/services-docker/octavia.yaml \
          -e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml \
          --set ceph_namespace={{additional_ceph_insecure_registry}}{{container_ceph_namespace}}  \
          --set ceph_image={{container_ceph_image}} --set ceph_tag={{container_ceph_tag}} \
          --output-images-file /home/stack/templates/overcloud_containers.yaml

    - name: Pull images using the container_images.yaml
      shell: |
        set -o pipefail
        . /home/stack/stackrc
        { time openstack overcloud container image upload --config-file /home/stack/templates/overcloud_containers.yaml 2>&1 | tee -a {{log_dir}}/container-image-upload.log ; } 2>> {{log_dir}}/container-image-upload.log
      become: true

    - name: Create template for using images from local registry
      shell: |
        . /home/stack/stackrc
        openstack overcloud container image prepare --namespace 192.168.0.1:8787{{container_namespace}} \
          --prefix openstack --tag {{container_tag}} --set ceph_namespace=192.168.0.1:8787{{container_ceph_namespace}} \
          --set ceph_image={{container_ceph_image}} --set ceph_tag={{container_ceph_tag}} \
          -e /usr/share/openstack-tripleo-heat-templates/environments/services-docker/octavia.yaml \
          -e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml \
          --output-env-file /home/stack/templates/docker_registry.yaml
  rescue:
    - name: Update motd on failure
      include_role:
        name: update-motd
      vars:
        update_motd: Undercloud container registry failures

    - name: Ensure playbook stops under this condition
      fail:
        msg: Undercloud container registry failures
  always:
    - name: Collect Setup Container Registry Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/alderaan-deploy_log"
        mode: pull
